server.port=8080
# Spring Cloud Gateway
spring.application.name=api-gateway
# Spring DevTools
spring.devtools.restart.enabled=true
# Override Spring beans
spring.main.allow-bean-definition-overriding=true


#Eureka Server
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

#Log
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO

#Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs

